config/routes.rb
Ftop::Application.routes.draw do

  resources :members

  match 'time_entries/report' => 'time_entries#report'

  root :to => 'time_entries#new'

  resources :time_entries

end

app/models/time_entry.rb
class TimeEntry < ActiveRecord::Base
  attr_accessible :coop_id, :date_worked, :hours_worked, :description

  belongs_to :member,
             inverse_of: :time_entries

  validates_presence_of :date_worked,
  											:hours_worked
  											
  #validates_presence_of :member, :message => ""
  validates_presence_of :coop_id, :message => "is invalid."
	
	validates_numericality_of :hours_worked, greater_than: 0

  # Callbacks
  after_save :update_member_month_report
  before_destroy :remove_member_month_report_hours
  
  def update_member_month_report
    report = member.member_month_reports.for_date(created_at)
    report.hours_worked += hours_worked - (hours_worked_was || 0)
    report.save!
  end
  
  def remove_member_month_report_hours
    #if a time entry is removed, delete the hours associated with its report
    report = member.member_month_reports.for_date(created_at)
    report.hours_worked -= hours_worked_was
    report.save!
  end

  # Virtual Attributes
  # when time entry form submits coop_id, find a member & set it
  def coop_id=(id)
    self.member = Member.find_by_coop_id(id)
  end
  
  def coop_id
    member.try(:coop_id)
  end
end

app/controllers/time_entries_controller.rb
class TimeEntriesController < ApplicationController
  # GET /time_entries
  # GET /time_entries.json
  def index
    @time_entries = TimeEntry.order("date_worked DESC").all
    #@supervisors = Member.where(supervisor: true)
    #@member = Member.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @time_entries }
    end
  end

  # GET /time_entries/1
  # GET /time_entries/1.json
  def show
    @time_entry = TimeEntry.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @time_entry }
    end
  end

  # GET /time_entries/report
  # GET /time_entries/reort.json
  def report

    @startD = params[:start].to_time
    @endD = params[:end].to_time 
    

    #grab all MemberMonthReports which fall within date constraints
    @reports = MemberMonthReport.
      where('? <= start_date and start_date <= ?', @startD, @endD).
      reorder(:start_date, :member_id)
    
    respond_to do |format|
      format.html # report.html.erb
      format.json { render json: @time_entries }
    end
  end

  # GET /time_entries/new
  # GET /time_entries/new.json
  def new
    @time_entry = TimeEntry.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @time_entry }
    end
  end

  # GET /time_entries/1/edit
  def edit
    @time_entry = TimeEntry.find(params[:id])
  end

  # POST /time_entries
  # POST /time_entries.json
  def create
    @time_entry = TimeEntry.new(params[:time_entry])

    respond_to do |format|
      if @time_entry.save
        format.html { redirect_to @time_entry, notice: 'Time entry was successfully created.' }
        format.json { render json: @time_entry, status: :created, location: @time_entry }
      else
        format.html { render action: "new" }
        format.json { render json: @time_entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /time_entries/1
  # PUT /time_entries/1.json
  def update
    @time_entry = TimeEntry.find(params[:id])

    respond_to do |format|
      if @time_entry.update_attributes(params[:time_entry])
        format.html { redirect_to @time_entry, notice: 'Time entry was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @time_entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /time_entries/1
  # DELETE /time_entries/1.json
  def destroy
    @time_entry = TimeEntry.find(params[:id])
    @time_entry.destroy

    respond_to do |format|
      format.html { redirect_to time_entries_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/time_entries_helper.rb
module TimeEntriesHelper
end

app/views/time_entries/_form.html.erb
<%= form_for(@time_entry) do |f| %>
  <% if @time_entry.errors.any? %>
    <div id="error_explanation">
      <p class="italic"><%= pluralize(@time_entry.errors.count, "error") %> prohibited this Time Entry from being saved:</p>

      <% @time_entry.errors.full_messages.each do |msg| %>
        <p><%= msg %></p>
      <% end %>
      <p class="bold">Please correct the errors and try again. Still having trouble? Please <%= mail_to "bfcftop@gmail.com", "email us", :encode => "javascript", :subject => "Please add me to the BFC FTOP system", :body => "Include your full name and Coop ID" %></p>
    </div>
  <% end %>

  <table class="entry">
    <tr>
      <td><%= f.label 'Food Coop Id#' %></td>
      <td><%= f.text_field :coop_id, :placeholder => '12345A' %></td>
    </tr>



    <tr>
      <td><%= f.label 'Date Worked', :placeholder => 'yyyy-mm-dd' %></td>



      <td><%= f.text_field :date_worked, :placeholder => 'yyyy-mm-dd',  'data-behaviour'=>'datepicker' %></td>
    </tr>

    <tr>
      <td><%= f.label 'Number of Hours' %></td>
      <td><%= f.text_field :hours_worked, :placeholder => '0.00' %></td>
    </tr>

    <tr>
      <td valign="top"><%= f.label 'Description' %></td>
      <td><%= f.text_area :description, :placeholder => 'optional', :rows => 5 %></td>
    </tr>

    <tr>
      <td>&nbsp;</td>
      <td><div class="actions">
    <%= f.submit ">> Submit Time" %>
  </div></td>
    </tr>

  </table>

  
  
<% end %>

app/views/time_entries/edit.html.erb
<h1>Editing time_entry</h1>

<%= render 'form' %>

<%= link_to 'Show', @time_entry %> |
<%= link_to 'Back', time_entries_path %>

app/views/time_entries/index.html.erb
<h1>Listing All Time Entries</h1>

<table border="1" cellpadding="5" cellspacing="5" class="sortable">
  <thead>
  <tr>
    <th>Date Entered</th>
    <th>Date Worked</th>
    <th>Coop ID</th>
    <th>Name</th>
    <th>Hours Entered</th>
    <th>Description</th>
    <th></th>
    <th></th>
  </tr>
  </thead>

<% @time_entries.each do |time_entry| %>
  <tr>
    <td><%= time_entry.created_at.strftime("%m/%d/%Y") %></td>
    <td><%= time_entry.date_worked.strftime("%m/%d/%Y") %></td>
    <td><%= time_entry.member.coop_id %></td>

    <td><%= time_entry.member.first_name %> <%= time_entry.member.last_name %> </td>

    <td><%= time_entry.hours_worked %> </td>
    <td><%= time_entry.description %> </td>

    <td><%= link_to 'Edit', edit_time_entry_path(time_entry) %></td>
    <td>

      <%= button_to "delete", time_entry, confirm: 'Are you sure?', :method=>:delete, :class=>:destroy %>
    </td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Time entry', new_time_entry_path %>

app/views/time_entries/new.html.erb
<div id="form-wrapper">
	<h1>Enter your time here!</h1>
	<p class="italic small">For FTOP Credits at the Park Slope Food Coop<br/>
  (You must be registered.  Not registered?, <%= mail_to "bfcftop@gmail.com", "email us", :encode => "javascript", :subject => "Please add me to the BFC FTOP system", :body => "Include your full name and Coop ID" %> to get registered)</p>
<%= render 'form' %>
</div>

<script type="text/javascript">
	$(document).on("focus", "[data-behaviour~='datepicker']", function(e){
    $(this).datepicker({"format": "yyyy-mm-dd", "weekStart": 1, "autoclose": true});
});
</script>

app/views/time_entries/report.html.erb
<h1>Time Entries Report</h1>

<span class='bold'>Today's Date:</span> <%= Date.today.strftime("%B %d, %Y") %><br/>
<span class='bold'>Start Date:</span> <%= @startD.strftime("%B %d, %Y") %><br/>
<span class='bold'>End Date:</span> <%= @endD.strftime("%B %d, %Y") %><br/><br/>

<table border="1" cellpadding="5" cellspacing="5">
  <tr>
    <td><strong>First Name</strong></td>
    <td><strong>Last Name</strong></td>
    <td><strong>Coop ID</strong></td>
    <td><strong>Shifts</strong></td>
    
   </tr> 

<% @reports.each do |report| %>
<% if report.shifts_worked > 0 %>
  <tr>
    <td><%= report.member.first_name %></td>
    <td><%= report.member.last_name %></td>
    <td><%= report.member.coop_id %></td>
    <td><%= report.shifts_worked %></td>
  </tr>
  <% end %>
<% end %>
</table>

app/views/time_entries/show.html.erb
<div id="form-wrapper">
	<h1>Thanks for entering your time!</h1>
	<p>Name: <span class='bold'><%= @time_entry.member.full_name %></span><br/>
Park Slope Food Coop Id#: <span class='bold'><%= @time_entry.member.coop_id %></span><br/>

Hours You Entered: <span class='bold'><%= @time_entry.hours_worked %></span><br/>

</p>
</div>