config/routes.rb
Ftop::Application.routes.draw do

  resources :members

  match 'time_entries/report' => 'time_entries#report'

  root :to => 'time_entries#new'

  resources :time_entries

end

app/models/member.rb
class Member < ActiveRecord::Base
  attr_accessible :coop_id, :first_name, :last_name, :email_address

  has_many :time_entries,
           inverse_of: :member,
           dependent: :destroy

  has_many :member_month_reports,
           inverse_of: :member,
           dependent: :destroy

  validates_presence_of :coop_id,
  						          :first_name,
  						          :last_name,
  						          :email_address

  validates_uniqueness_of :email_address, :coop_id

  def full_name
  	first_name + " " + last_name
  end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  # GET /members
  # GET /members.json
  def index
    @members = Member.order(:first_name)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @members }
    end
  end

  # GET /members/1
  # GET /members/1.json
  def show
    @member = Member.find(params[:id])
    
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @member }
    end
  end

  # GET /members/new
  # GET /members/new.json
  def new
    @member = Member.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @member }
    end
  end

  # GET /members/1/edit
  def edit
    @member = Member.find(params[:id])
  end

  # POST /members
  # POST /members.json
  def create
    @member = Member.new(params[:member])

    respond_to do |format|
      if @member.save
        format.html { redirect_to '/members', notice: 'Member was successfully created.' }
        format.json { render json: @member, status: :created, location: @member }
      else
        format.html { render action: "new" }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /members/1
  # PUT /members/1.json
  def update
    @member = Member.find(params[:id])

    respond_to do |format|
      if @member.update_attributes(params[:member])
        format.html { redirect_to '/members', notice: 'Member was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /members/1
  # DELETE /members/1.json
  def destroy
    @member = Member.find(params[:id])
    @member.destroy

    respond_to do |format|
      format.html { redirect_to '/members', notice: 'Member was successfully deleted.' }
      format.json { head :no_content }
    end
  end
end

app/helpers/members_helper.rb
module MembersHelper
end

app/views/members/_form.html.erb
<%= form_for(@member) do |f| %>
  <% if @member.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@member.errors.count, "error") %> prohibited this member from being saved:</h2>

      <ul>
      <% @member.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.label 'Coop Id' %>
  <%= f.text_field :coop_id %>
  <%= f.label 'First Name' %>
  <%= f.text_field :first_name %>
  <%= f.label 'Last Name' %>
  <%= f.text_field :last_name %>
  <%= f.label 'Email Address' %>
  <%= f.text_field :email_address %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/members/edit.html.erb
<h1>Editing member</h1>

<%= render 'form' %>

<%= link_to 'Show', @member %> |
<%= link_to 'Back', members_path %>

app/views/members/index.html.erb
<h1>Listing members</h1>

<table class="members">
  <tr>
    <td class="title">Coop ID</td>
    <td class="title">Name</td>
    <td class="title">Email Address</td>
    <td></td>
    <td></td>
  </tr>

<% @members.each do |member| %>
  <tr>
    <td style="font-weight:bold;"><%= member.coop_id %></td>
    <td><%= member.full_name %></td>
    <td><%= mail_to member.email_address %></td>
    <td class="editbtn"><%= link_to 'Edit', edit_member_path(member) %></td>
    <td class="editbtn">

      <%= button_to "delete", member, confirm: 'Are you sure?', :method=>:delete, :class=>:destroy %></td>

  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Member', new_member_path %>

app/views/members/new.html.erb
<h1>New member</h1>

<%= render 'form' %>

app/views/members/show.html.erb
<h2><%= mail_to @member.email_address, @member.full_name %> : <%= @member.coop_id %></h2>